In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

# Numpy Arrays

In [3]:
num_list = [1,2,3,4,5]

In [4]:
np_arr = np.array(num_list)

In [5]:
np_arr

array([1, 2, 3, 4, 5])

In [6]:
num_list_2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np_arr_2 = np.array(num_list_2)

In [8]:
np_arr_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [12]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [13]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
np.random.rand(5)

array([0.92321354, 0.36396412, 0.88442738, 0.13868901, 0.45952103])

In [15]:
np.random.randn(100)

array([-1.47268647e+00, -1.59081282e+00,  1.75064517e+00,  8.22143837e-01,
       -4.23416136e-01,  7.01526191e-01,  1.41595586e-01,  7.09413269e-01,
        7.04011754e-01, -1.06187070e+00,  4.98879537e-01,  1.55038698e+00,
       -1.02696927e+00,  9.50679417e-01, -3.76806396e-01,  3.02658776e-01,
       -2.65283764e-02,  1.29775903e+00,  1.54269805e+00,  7.07737110e-01,
        9.65072781e-01,  3.11670456e-01,  1.33783883e-01,  1.48630032e+00,
       -5.10004152e-01,  4.61543462e-01,  2.61382467e-01,  1.21601555e+00,
       -1.04185400e+00, -2.57741623e-01,  8.32162627e-01,  4.62556994e-01,
        2.02248652e-01,  7.92895121e-01, -1.77043411e+00, -9.16128513e-01,
        1.29685125e+00, -1.33139163e+00, -1.06542657e+00,  1.15076110e+00,
        2.02412472e+00, -1.02014046e+00, -9.49894763e-01, -3.57763343e-01,
        5.07808154e-01, -1.08612971e+00, -1.79061567e+00,  8.69481472e-02,
       -5.48380897e-01, -1.51328500e+00, -1.71308075e+00, -8.71948124e-01,
        2.69832449e-01, -

In [16]:
arr = np.random.randint(1,100,10).reshape(2,5)
arr

array([[25, 12, 66, 61,  1],
       [73,  2, 79, 55, 28]])

In [17]:
arr.max()

79

In [18]:
arr.argmax()

7

In [19]:
arr.min()

1

In [20]:
arr.argmin()

4

In [21]:
arr.shape

(2, 5)

In [22]:
arr.dtype

dtype('int64')

In [23]:
# prompt: arr turn to int32

import numpy as np
arr = arr.astype(np.int32)
arr.dtype


dtype('int32')

# Numpy Practices

In [24]:
zeros = np.zeros(3)
zeros

array([0., 0., 0.])

In [25]:
zeros + 5

array([5., 5., 5.])

In [26]:
ones = np.ones(5)
ones

array([1., 1., 1., 1., 1.])

In [27]:
print(ones*5)

[5. 5. 5. 5. 5.]


In [28]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [29]:
nums = np.arange(9)
nums

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [30]:
nums.reshape (3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
np.random.rand

<function RandomState.rand>

In [32]:
np.random.rand(5)

array([0.47045633, 0.16283117, 0.90636436, 0.32849335, 0.90020248])

In [33]:
np.random.randint(9)

3

In [34]:
np.random.randint(9,size=9)

array([1, 5, 5, 4, 6, 5, 8, 1, 4])

In [35]:
np.random.randint(5,size=9).reshape(3,3)

array([[3, 2, 0],
       [0, 0, 0],
       [3, 2, 1]])

In [36]:
np.random.exponential(scale=1)

0.22646118921857014

In [37]:
np.random.exponential(size=5)

array([1.43222671, 0.83493337, 0.25283269, 0.54861487, 0.050943  ])

In [38]:
np.random.exponential(scale=1,size=5)

array([0.31423819, 1.56089764, 0.45679078, 0.407811  , 1.72190843])

In [39]:
np.random.randn(25) # 25 rand numbers from a standard normal distribution

array([ 0.62089787, -0.17483899, -1.40670563, -1.76760623, -0.92065776,
        1.15078719, -1.1142185 ,  1.0327882 ,  0.69131492,  0.00947023,
        1.08167481,  0.75265659,  0.82748195, -0.01164639,  1.50685555,
        0.19032869,  0.2696154 ,  0.81377969,  0.12456269, -0.39668852,
        1.29398212,  0.94631002,  1.68906861,  0.04178456,  0.25587912])

In [40]:
np.random.randn(25).shape

(25,)

In [41]:
# create a  matrix from 0.01 to 1
# solution 1

In [42]:
np.arange(1,101) / 100 # arange gives you 1 - 100

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [43]:
np.linspace(0.01,1,100).reshape(2,2,5,5) # 4 dimention on 5*5

array([[[[0.01, 0.02, 0.03, 0.04, 0.05],
         [0.06, 0.07, 0.08, 0.09, 0.1 ],
         [0.11, 0.12, 0.13, 0.14, 0.15],
         [0.16, 0.17, 0.18, 0.19, 0.2 ],
         [0.21, 0.22, 0.23, 0.24, 0.25]],

        [[0.26, 0.27, 0.28, 0.29, 0.3 ],
         [0.31, 0.32, 0.33, 0.34, 0.35],
         [0.36, 0.37, 0.38, 0.39, 0.4 ],
         [0.41, 0.42, 0.43, 0.44, 0.45],
         [0.46, 0.47, 0.48, 0.49, 0.5 ]]],


       [[[0.51, 0.52, 0.53, 0.54, 0.55],
         [0.56, 0.57, 0.58, 0.59, 0.6 ],
         [0.61, 0.62, 0.63, 0.64, 0.65],
         [0.66, 0.67, 0.68, 0.69, 0.7 ],
         [0.71, 0.72, 0.73, 0.74, 0.75]],

        [[0.76, 0.77, 0.78, 0.79, 0.8 ],
         [0.81, 0.82, 0.83, 0.84, 0.85],
         [0.86, 0.87, 0.88, 0.89, 0.9 ],
         [0.91, 0.92, 0.93, 0.94, 0.95],
         [0.96, 0.97, 0.98, 0.99, 1.  ]]]])

In [44]:
np.linspace(0,1,20) # 20 linearly spaced points 0-1

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## numpy indexing and selection

In [45]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [46]:
mat[2:] # row 2 - end

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [47]:
mat[2:,:1] # row 2 , col 0

array([[11],
       [16],
       [21]])

In [48]:
mat[2:,:2] # row 2 - col 0 and 1

array([[11, 12],
       [16, 17],
       [21, 22]])

In [49]:
mat[2:,1:2]

array([[12],
       [17],
       [22]])

In [50]:
mat[2:,1:2].shape

(3, 1)

In [51]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [52]:
mat[2:,1]

array([12, 17, 22])

In [53]:
mat[3,4]

20

In [54]:
mat.shape

(5, 5)

In [55]:
# Since mat[1][1] will always be 7, the if condition is redundant.
# We can directly print all elements of 'mat' using a nested loop:

for i in range(mat.shape[0]):  # Iterate through rows
    for j in range(mat.shape[1]):  # Iterate through columns
        if mat[i,j] == 20:
          print(i,j, mat[i, j])

3 4 20


range(mat.shape[0], mat.shape[1]): This creates a sequence of numbers starting from mat.shape[0] (5) and ending before mat.shape[1] (5). It generates a sequence from 5 to 5 (non-inclusive). Because the start and end is the same, this range is empty meaning it has no values.

In [56]:
for i,j in range(mat.shape[0], mat.shape[1]):
  print (i,j)
  # if mat[i,j] == 20 :
  #   print(i,j, mat[i,j])

In [57]:
# last row
mat[4:,:]

array([[21, 22, 23, 24, 25]])

In [58]:
# last row
mat[-1:,:]

array([[21, 22, 23, 24, 25]])

In [59]:
new_arr = np.arange(1,10)
new_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
slice_of_new_arr = new_arr[:6]
slice_of_new_arr

array([1, 2, 3, 4, 5, 6])

In [61]:
slice_of_new_arr[:] = 99
slice_of_new_arr

array([99, 99, 99, 99, 99, 99])

In [62]:
new_arr

array([99, 99, 99, 99, 99, 99,  7,  8,  9])

In [63]:
arr_copy = new_arr.copy() # copy the array
arr_copy

array([99, 99, 99, 99, 99, 99,  7,  8,  9])

In [64]:
arr_copy [:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100])

In [65]:
new_arr

array([99, 99, 99, 99, 99, 99,  7,  8,  9])

In [66]:
# prompt: generate a 2d array

import numpy as np
# Create a 2D array (matrix) with random integers
rows = 5  # Number of rows
cols = 3  # Number of columns
min_val = 1
max_val = 10

two_d_array = np.random.randint(min_val, max_val + 1, size=(rows, cols))

two_d_array


array([[10,  1, 10],
       [ 8,  9,  2],
       [ 6,  3,  1],
       [ 5,  5,  5],
       [ 7,  7,  4]])

In [67]:
two_d_array[1][1]

9

In [68]:
two_d_array[1,1]

9

In [69]:
two_d_array[2,1] + new_arr[2]

102

In [70]:
two_d_array * two_d_array

array([[100,   1, 100],
       [ 64,  81,   4],
       [ 36,   9,   1],
       [ 25,  25,  25],
       [ 49,  49,  16]])

In [71]:
two_d_array / two_d_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [72]:
two_d_array ** 1.3534535

array([[22.56594369,  1.        , 22.56594369],
       [16.68362055, 19.56693779,  2.55523061],
       [11.30294289,  4.42345315,  1.        ],
       [ 8.8312748 ,  8.8312748 ,  8.8312748 ],
       [13.92518264, 13.92518264,  6.52920347]])

In [73]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [75]:
arr < 9

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
       False])

In [76]:
arr > 4 , arr < 9

(array([False, False, False, False,  True,  True,  True,  True,  True,
         True]),
 array([ True,  True,  True,  True,  True,  True,  True,  True, False,
        False]))

In [77]:
arr > 4 , # what happens here ??
arr < 9

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
       False])

In [78]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

# math

In [79]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [80]:
np.sum(mat)

325

In [81]:
mat.sum()

325

In [82]:
np.std(mat)

7.211102550927978

In [83]:
mat.std()

7.211102550927978

In [84]:
# sum of all cols
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [85]:
# sum of all rows
mat.sum(axis=1)

array([ 15,  40,  65,  90, 115])

# Numpy Opreations

In [86]:
arr = np.arange(0,11)

In [87]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])