In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

# Numpy Arrays

In [2]:
num_list = [1,2,3,4,5]

In [3]:
np_arr = np.array(num_list)

In [4]:
np_arr

array([1, 2, 3, 4, 5])

In [5]:
num_list_2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np_arr_2 = np.array(num_list_2)

In [7]:
np_arr_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [54]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [56]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [58]:
np.random.rand(5)

array([0.69290882, 0.9666298 , 0.31651719, 0.74966357, 0.73626047])

In [59]:
np.random.randn(100)

array([ 8.31509275e-01,  1.36831966e+00, -1.17626843e+00,  7.55619255e-01,
       -6.77660216e-02,  1.13084580e+00,  7.73421418e-01,  1.80040700e+00,
        5.95576115e-01, -9.13286302e-01, -7.85885799e-01,  1.37278795e+00,
        2.87191334e-01, -4.85501767e-01,  1.34508008e+00, -7.04143784e-01,
       -1.68147509e+00, -7.95677889e-01,  1.93639309e+00, -7.78714992e-01,
       -1.05791109e+00, -2.87388940e-01, -7.93713786e-01,  1.06214906e+00,
        4.48038866e-01, -3.90418880e-02, -7.25793879e-01, -2.78242509e-01,
       -1.17989444e+00, -3.71201072e-01, -9.89713309e-01, -1.76658243e-01,
        2.34904356e+00, -5.86612054e-02,  5.01726801e-01, -3.57617440e-01,
       -9.56587748e-01, -5.98627400e-02, -7.55488382e-01,  2.14079765e+00,
        9.66660413e-02, -2.01575811e-02,  1.28972643e+00,  7.87988299e-01,
       -2.98778989e-01,  1.44518877e+00, -1.91404284e-01, -4.73592648e-02,
       -1.45411232e-01,  1.81481773e+00, -9.84771318e-01,  2.34694662e+00,
       -7.06438835e-01,  

In [68]:
arr = np.random.randint(1,100,10).reshape(2,5)
arr

array([[54, 75, 44, 67, 23],
       [77, 79, 74, 33, 75]])

In [69]:
arr.max()

79

In [71]:
arr.argmax()

6

In [70]:
arr.min()

23

In [72]:
arr.argmin()

4

In [73]:
arr.shape

(2, 5)

In [75]:
arr.dtype

dtype('int64')

In [76]:
# prompt: arr turn to int32

import numpy as np
arr = arr.astype(np.int32)
arr.dtype


dtype('int32')

# Numpy Practices

In [11]:
zeros = np.zeros(3)
zeros

array([0., 0., 0.])

In [12]:
zeros + 5

array([5., 5., 5.])

In [13]:
ones = np.ones(5)
ones

array([1., 1., 1., 1., 1.])

In [14]:
print(ones*5)

[5. 5. 5. 5. 5.]


In [15]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
nums = np.arange(9)
nums

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
nums.reshape (3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
np.random.rand

<function RandomState.rand>

In [19]:
np.random.rand(5)

array([0.16400561, 0.41411985, 0.31537413, 0.31101057, 0.64644476])

In [20]:
np.random.randint(9)

3

In [21]:
np.random.randint(9,size=9)

array([7, 7, 7, 2, 3, 1, 5, 0, 7])

In [22]:
np.random.randint(5,size=9).reshape(3,3)

array([[3, 4, 2],
       [2, 1, 4],
       [2, 3, 0]])

In [23]:
np.random.exponential(scale=1)

0.14644758548406617

In [24]:
np.random.exponential(size=5)

array([0.14143723, 0.95736326, 0.2609685 , 0.19719655, 0.15346098])

In [25]:
np.random.exponential(scale=1,size=5)

array([0.49003066, 0.42481996, 0.06824649, 0.21149986, 0.17881375])

In [26]:
np.random.randn(25) # 25 rand numbers from a standard normal distribution

array([ 0.9457096 , -2.08975936, -0.10120439,  0.9178201 ,  1.18841444,
       -0.40729885,  1.482753  , -0.72645905, -0.9193216 ,  0.82106246,
       -0.68488526,  0.90670262, -0.55755954, -0.07846309,  0.19056648,
        0.61964518, -1.73080039, -0.01854243, -0.58122407, -0.3664355 ,
        0.55025089, -0.20630648,  0.15724756, -1.56292462, -0.07916613])

In [27]:
np.random.randn(25).shape

(25,)

In [28]:
# create a  matrix from 0.01 to 1
# solution 1

In [29]:
np.arange(1,101) / 100 # arange gives you 1 - 100

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [30]:
np.linspace(0.01,1,100).reshape(2,2,5,5) # 4 dimention on 5*5

array([[[[0.01, 0.02, 0.03, 0.04, 0.05],
         [0.06, 0.07, 0.08, 0.09, 0.1 ],
         [0.11, 0.12, 0.13, 0.14, 0.15],
         [0.16, 0.17, 0.18, 0.19, 0.2 ],
         [0.21, 0.22, 0.23, 0.24, 0.25]],

        [[0.26, 0.27, 0.28, 0.29, 0.3 ],
         [0.31, 0.32, 0.33, 0.34, 0.35],
         [0.36, 0.37, 0.38, 0.39, 0.4 ],
         [0.41, 0.42, 0.43, 0.44, 0.45],
         [0.46, 0.47, 0.48, 0.49, 0.5 ]]],


       [[[0.51, 0.52, 0.53, 0.54, 0.55],
         [0.56, 0.57, 0.58, 0.59, 0.6 ],
         [0.61, 0.62, 0.63, 0.64, 0.65],
         [0.66, 0.67, 0.68, 0.69, 0.7 ],
         [0.71, 0.72, 0.73, 0.74, 0.75]],

        [[0.76, 0.77, 0.78, 0.79, 0.8 ],
         [0.81, 0.82, 0.83, 0.84, 0.85],
         [0.86, 0.87, 0.88, 0.89, 0.9 ],
         [0.91, 0.92, 0.93, 0.94, 0.95],
         [0.96, 0.97, 0.98, 0.99, 1.  ]]]])

In [31]:
np.linspace(0,1,20) # 20 linearly spaced points 0-1

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## numpy indexing and selection

In [32]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [33]:
mat[2:] # row 2 - end

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [34]:
mat[2:,:1] # row 2 , col 0

array([[11],
       [16],
       [21]])

In [35]:
mat[2:,:2] # row 2 - col 0 and 1

array([[11, 12],
       [16, 17],
       [21, 22]])

In [36]:
mat[2:,1:2]

array([[12],
       [17],
       [22]])

In [37]:
mat[2:,1:2].shape

(3, 1)

In [38]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [39]:
mat[2:,1]

array([12, 17, 22])

In [40]:
mat[3,4]

20

In [41]:
mat.shape

(5, 5)

In [42]:
# Since mat[1][1] will always be 7, the if condition is redundant.
# We can directly print all elements of 'mat' using a nested loop:

for i in range(mat.shape[0]):  # Iterate through rows
    for j in range(mat.shape[1]):  # Iterate through columns
        if mat[i,j] == 20:
          print(i,j, mat[i, j])

3 4 20


range(mat.shape[0], mat.shape[1]): This creates a sequence of numbers starting from mat.shape[0] (5) and ending before mat.shape[1] (5). It generates a sequence from 5 to 5 (non-inclusive). Because the start and end is the same, this range is empty meaning it has no values.

In [43]:
for i,j in range(mat.shape[0], mat.shape[1]):
  print (i,j)
  # if mat[i,j] == 20 :
  #   print(i,j, mat[i,j])

In [44]:
# last row
mat[4:,:]

array([[21, 22, 23, 24, 25]])

In [45]:
# last row
mat[-1:,:]

array([[21, 22, 23, 24, 25]])

In [91]:
new_arr = np.arange(1,10)
new_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
slice_of_new_arr = new_arr[:6]
slice_of_new_arr

array([1, 2, 3, 4, 5, 6])

In [89]:
slice_of_new_arr[:] = 99
slice_of_new_arr

array([99, 99, 99, 99, 99, 99])

In [93]:
new_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
arr_copy = new_arr.copy() # copy the array
arr_copy

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
arr_copy [:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100])

In [96]:
new_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
# prompt: generate a 2d array

import numpy as np
# Create a 2D array (matrix) with random integers
rows = 5  # Number of rows
cols = 3  # Number of columns
min_val = 1
max_val = 10

two_d_array = np.random.randint(min_val, max_val + 1, size=(rows, cols))

two_d_array


array([[ 5,  3,  8],
       [ 5,  1,  1],
       [ 5,  9,  3],
       [ 3,  2, 10],
       [ 4,  9,  7]])

In [104]:
two_d_array[1][1]

1

In [105]:
two_d_array[1,1]

1

In [106]:
two_d_array[2,1] + new_arr[2]

12

In [109]:
two_d_array * two_d_array

array([[ 25,   9,  64],
       [ 25,   1,   1],
       [ 25,  81,   9],
       [  9,   4, 100],
       [ 16,  81,  49]])

In [110]:
two_d_array / two_d_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [114]:
two_d_array ** 1.3534535

array([[ 8.8312748 ,  4.42345315, 16.68362055],
       [ 8.8312748 ,  1.        ,  1.        ],
       [ 8.8312748 , 19.56693779,  4.42345315],
       [ 4.42345315,  2.55523061, 22.56594369],
       [ 6.52920347, 19.56693779, 13.92518264]])

In [116]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [129]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [124]:
arr < 9

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
       False])

In [125]:
arr > 4 , arr < 9

(array([False, False, False, False,  True,  True,  True,  True,  True,
         True]),
 array([ True,  True,  True,  True,  True,  True,  True,  True, False,
        False]))

In [127]:
arr > 4 , # what happens here ??
arr < 9

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
       False])

In [130]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

# math

In [46]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [47]:
np.sum(mat)

325

In [48]:
mat.sum()

325

In [49]:
np.std(mat)

7.211102550927978

In [50]:
mat.std()

7.211102550927978

In [51]:
# sum of all cols
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [52]:
# sum of all rows
mat.sum(axis=1)

array([ 15,  40,  65,  90, 115])

# Numpy Opreations

In [134]:
arr = np.arange(0,11)

In [132]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])